### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by DjinNO** [seriohub/velero-ui#33]
Helm values:
```
global:
  veleroNamespace: velero

uiIngress:
  enabled: true
  ingressClassName: nginx
  metadata:
    annotations: []
  spec:
    tls:
    - hosts:
      - velero-ui.domain.com
      secretName: velero-ui-tls

```

Result: 
Unable to login, login button not working

Error in web ui:
<img width="737" alt="image" src="https://github.com/user-attachments/assets/1c39b23f-926d-4270-8f9a-b736b2514dda">

❯ velero version
Client:
	Version: v1.14.0
	Git commit: none
Server:
	Version: v1.14.0

velero ui: Helm release 0.1.12

**Comment by davideserio** [comment]
Can you add these lines in your values-override.yaml?

```
uiNp:
  enabled: false
```  

Let me know whether the installation was successful or not.

**Comment by DjinNO** [comment]
> Can you add these lines in your values-override.yaml?
> 
> ```
> uiNp:
>   enabled: false
> ```
> 
> Let me know whether the installation was successful or not.

I'm already tried it (because I don't need NodePort) and had same issue

**Comment by DjinNO** [comment]
```
global:
  veleroNamespace: velero

uiIngress:
  enabled: true
  ingressClassName: nginx
  metadata:
    annotations: []
  spec:
    tls:
    - hosts:
      - velero-ui.domain.com
      secretName: velero-ui-tls
```
I have nothing else, only this config

**Comment by davideserio** [comment]
This configuration is working.
Can you verify the data in the config map velero-ui-config? 
If the url in NEXT_PUBLIC_VELERO_API_URL_1 and NEXT_PUBLIC_VELERO_API_WS_1 are correct, try restarting the velero-ui deployment.

**Comment by DjinNO** [comment]
```
data:
  NEXT_PUBLIC_REFRESH_DATATABLE_AFTER: "1500"
  NEXT_PUBLIC_REFRESH_RECENT: "5000"
  NEXT_PUBLIC_VELERO_API_NAME_1: <cluster-name>
  NEXT_PUBLIC_VELERO_API_URL_1: http://:30001/api
  NEXT_PUBLIC_VELERO_API_WS_1: ws://:30001
```
Of Course I tried to install velero-ui multiple times
I'm using port-forward to access UI

**Comment by davideserio** [comment]
The configmap is wrong. 
I tried the your values-override.yaml is working. 
Can you try to install from scratch and verify the contents of the configmap? 
It is important to disable uiNp if it is not used

```
uiNp:
  enabled: false
```

**Comment by DjinNO** [comment]
From scratch:

My vaules:
```
global:
  veleroNamespace: velero

uiNp:
  enabled: false

uiIngress:
  enabled: true
  ingressClassName: nginx
  metadata:
    annotations: []
  spec:
    tls:
    - hosts:
      - velero-ui.domain.com
      secretName: velero-ui-tls


```

Configmap:
```
❯ k get configmaps  -o yaml velero-ui-config
apiVersion: v1
data:
  NEXT_PUBLIC_REFRESH_DATATABLE_AFTER: "1500"
  NEXT_PUBLIC_REFRESH_RECENT: "5000"
  NEXT_PUBLIC_VELERO_API_NAME_1: <cluster-name>
  NEXT_PUBLIC_VELERO_API_URL_1: https://velero-ui.domain.com/api
  NEXT_PUBLIC_VELERO_API_WS_1: wss://velero-ui.domain.com
 ```
 
 The same problem. I also tried to set global.clusterName: velero 


logs from api pod:
k logs vui-api-79d6cb648d-q4tt9 | grep -i error | c
```
INFO      [Env creation] key: SECURITY_TOKEN_KEY value:                          validation:ERROR NOT A VALID SECRET KEY
INFO      [Env creation] key: SECURITY_REFRESH_TOKEN_KEY value:                          validation:ERROR NOT A VALID SECRET KEY
(trapped) error reading bcrypt version
AttributeError: module 'bcrypt' has no attribute '__about__'
[91mERROR:    2024-07-16 09:42:51.291 [helper.velero_client] ./velero-client/dl/velero-v1.12.2-linux-amd64.tar.gz is not a valid tarball file.[0m
[91mERROR:    2024-07-16 09:42:51.291 [helper.velero_client] Init velero client failed.[0m
[91mERROR:    2024-07-16 09:42:51.292 [helper.velero_client] E=Error extract velero, F=/app/helpers/velero_client.py, L=245[0m
[91mERROR:    2024-07-16 09:42:51.292 [helper.velero_client] an forced exit code(100) is called[0m
[91mERROR:    2024-07-16 09:42:51.329 [helper.velero_client] ./velero-client/dl/velero-v1.12.2-linux-amd64.tar.gz is not a valid tarball file.[0m
[91mERROR:    2024-07-16 09:42:51.329 [helper.velero_client] Init velero client failed.[0m
[91mERROR:    2024-07-16 09:42:51.330 [helper.velero_client] E=Error extract velero, F=/app/helpers/velero_client.py, L=245[0m
[91mERROR:    2024-07-16 09:42:51.330 [helper.velero_client] an forced exit code(100) is called[0m
[91mERROR:    2024-07-16 09:42:51.412 [helper.velero_client] Init velero client failed.[0m
[91mERROR:    2024-07-16 09:42:51.413 [helper.velero_client] E=Compressed file ended before the end-of-stream marker was reached, F=/usr/local/lib/python3.10/gzip.py, L=507[0m
[91mERROR:    2024-07-16 09:42:51.413 [helper.velero_client] an forced exit code(100) is called[0m

```

**Comment by DjinNO** [comment]
> Now the config map has the correct syntax, but you should correctly configure the url **velero-ui.domain.com** . It also verifies that the velero api can connect to the Internet to download the velero client.

What if I wouldn't like to expose velero ui? It's very strange approach

**Comment by DjinNO** [comment]
```
global:
  veleroNamespace: velero
  clusterName: velero

uiNp:
  enabled: true

uiIngress:
  enabled: false
  ingressClassName: nginx
  metadata:
    annotations: []
  spec:
    tls:
    - hosts:
      - velero-ui.domain.com
      secretName: velero-ui-tls

```

This configuration doesn't work either :(
