### ISSUE TITLE
Resource policies in Backup

### ISSUE THREAD

**Issue by davideserio** [seriohub/velero-ui#39]
I have one more question. For some of the namespaces, I would like to use volumePolicies during backup. I have prepared 
```yaml
ConfigMaps for these:
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-policies-exclude-cm
  namespace: velero
data:
  nfs-policies.yaml: |
    version: v1
    volumePolicies:
      - conditions:
          nfs:
            server: 192.168.1.10
            path: /srv/volume1
        action:
          type: skip
      - conditions:
          nfs:
            server: 192.168.1.40
            path: /srv/volume2
        action:
          type: skip
```
Is there a way to set this in the GUI when creating a backup?
Resource policies: https://velero.io/docs/main/resource-filtering/

_Originally posted by @speedkup in https://github.com/seriohub/velero-ui/issues/38#issuecomment-2270612476_
